name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        uses: JoonasVali/Native-Android-Build@v1
        with:
          project-dir: .
